google/wasefire

crates/xtask/src/main.rs

Also don't rely on the name of the crate to be the same as the crate directory.

Support applet path for Rust

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/lib.rs
crates/api/CHANGELOG.md
crates/api/Cargo.toml
crates/prelude/CHANGELOG.md
crates/prelude/Cargo.toml
crates/prelude/src/lib.rs
crates/prelude/test.sh
examples/rust/hello/src/lib.rs
examples/rust/hello/test.sh

Add test feature in Rust prelude

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/lib.rs

Add tests that link names are unique

---

crates/xtask/src/main.rs
scripts/ci.sh

They are now well maintainable and not that useful.

Remove list-applets, build-applets, and build-runners

---

.github/workflows/ci.yml
.gitignore
crates/xtask/src/main.rs
scripts/ci.sh
scripts/pages.sh
scripts/setup.sh
scripts/upgrade.sh
scripts/wrapper.sh

Add wrapper script to install dependencies on demand

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/scheduling.rs
crates/board/CHANGELOG.md
crates/board/src/lib.rs
crates/prelude/CHANGELOG.md
crates/prelude/src/scheduling.rs
crates/runner-host/src/board.rs
crates/runner-host/src/main.rs
crates/runner-host/test.sh
crates/runner-nordic/src/tasks/mod.rs
crates/runner-nordic/test.sh
crates/scheduler/CHANGELOG.md
crates/scheduler/src/call/scheduling.rs
examples/assemblyscript/api.ts
examples/rust/timer_test/src/lib.rs
scripts/hwci-nordic.sh
scripts/wrapper.sh

Extend applet API with scheduling::breakpoint

---

crates/runner-host/Cargo.lock
crates/runner-host/src/main.rs
crates/runner-nordic/Cargo.lock
crates/runner-nordic/src/main.rs
crates/scheduler/CHANGELOG.md
crates/scheduler/Cargo.lock
crates/scheduler/Cargo.toml
crates/scheduler/src/lib.rs
crates/scheduler/test.sh

Abstract the scheduler over the applet

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/button.rs
crates/api-desc/src/clock.rs
crates/api-desc/src/crypto.rs
crates/api-desc/src/crypto/gcm.rs
crates/api-desc/src/crypto/hash.rs
crates/api-desc/src/led.rs
crates/api-desc/src/lib.rs
crates/api-desc/src/macros.rs
crates/api-desc/src/store.rs
crates/api-desc/src/usb.rs
crates/api-desc/src/usb/serial.rs
examples/assemblyscript/api.ts

Require enum values in applet API

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/debug.rs
crates/api/test.sh
crates/board/CHANGELOG.md
crates/board/Cargo.lock
crates/board/src/debug.rs
crates/logger/CHANGELOG.md
crates/logger/Cargo.lock
crates/logger/Cargo.toml
crates/logger/src/lib.rs
crates/prelude/CHANGELOG.md
crates/prelude/src/debug.rs
crates/runner-host/Cargo.lock
crates/runner-host/src/board/debug.rs
crates/runner-nordic/src/systick.rs
crates/scheduler/CHANGELOG.md
crates/scheduler/src/call/debug.rs
examples/assemblyscript/api.ts
examples/rust/clock/Cargo.lock
examples/rust/clock/Cargo.toml
examples/rust/clock/src/lib.rs

Also improve the systick implementation for Nordic.

Add debug::time() for performance measurement

---

scripts/package.sh
scripts/system.sh

Do not use the nodesource repository if the system has a recent version.
Fixes #216

Update Node.js installation procedure

---

.gitignore
scripts/ci.sh
scripts/git.sh
scripts/publish.sh
scripts/upgrade.sh
scripts/wrapper.sh
taplo.toml

Also support cargo upgrade in wrapper.

Take .gitignore into account for find and taplo

---

.devcontainer/devcontainer.json
scripts/setup.sh
scripts/system.sh

Make the setup script support running without user input.

Simplify and fix post create command

---

crates/runner-host/Cargo.lock
crates/store/Cargo.lock
crates/xtask/Cargo.lock
examples/rust/hsm/host/Cargo.lock

Bump rustix for dependabot

---

.devcontainer/devcontainer.json

This is just an indication on how to do this, feel free to pick better files.

Open quick guide and "hello world" code automatically in new Codespaces

---

crates/xtask/src/main.rs

Use default optimization level when flag missing

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/platform.rs
crates/api-desc/src/platform/update.rs
crates/board/CHANGELOG.md
crates/board/src/platform.rs
crates/board/src/platform/update.rs
crates/prelude/CHANGELOG.md
crates/prelude/src/platform.rs
crates/prelude/src/platform/update.rs
crates/runner-nordic/src/tasks/platform.rs
crates/scheduler/CHANGELOG.md
crates/scheduler/src/applet/store.rs
crates/scheduler/src/applet/store/native.rs
crates/scheduler/src/applet/store/wasm.rs
crates/scheduler/src/call/platform.rs
crates/scheduler/src/call/platform/update.rs
crates/scheduler/src/call/store.rs
crates/scheduler/src/call/store/fragment.rs
examples/assemblyscript/api.ts

Add platform update API

---

examples/rust/opensk/Cargo.lock
examples/rust/opensk/src/lib.rs
examples/rust/opensk/src/user_presence.rs

Add impl for UserPresence

---

crates/api-desc/CHANGELOG.md
crates/api-desc/src/debug.rs
crates/prelude/CHANGELOG.md
crates/prelude/src/debug.rs
crates/scheduler/CHANGELOG.md
crates/scheduler/src/call/debug.rs
examples/assemblyscript/api.ts
examples/rust/clock/src/lib.rs

Make debug::time return isize

---

book/src/applet/prelude/uart.md
crates/api-desc/CHANGELOG.md
crates/api-desc/src/uart.rs
crates/board/CHANGELOG.md
crates/board/src/uart.rs
crates/error/CHANGELOG.md
crates/error/src/lib.rs
crates/prelude/CHANGELOG.md
crates/prelude/src/uart.rs
crates/runner-host/src/board/uart.rs
crates/runner-nordic/src/board/uart.rs
crates/scheduler/CHANGELOG.md
crates/scheduler/src/call/uart.rs
examples/assemblyscript/api.ts
examples/rust/echo/src/lib.rs
examples/rust/exercises/part-1-sol/src/lib.rs
examples/rust/exercises/part-2-sol/src/lib.rs
examples/rust/exercises/part-2/src/lib.rs
examples/rust/exercises/part-3-sol/src/lib.rs
examples/rust/exercises/part-3/src/lib.rs
examples/rust/exercises/part-4-sol/src/lib.rs
examples/rust/exercises/part-4/src/lib.rs
examples/rust/exercises/part-5/src/lib.rs
examples/rust/exercises/part-6-sol/src/lib.rs
examples/rust/exercises/part-6/src/lib.rs
examples/rust/exercises/part-7-sol/src/lib.rs
examples/rust/exercises/part-7/src/lib.rs

Add start/stop and set_baudrate functions for UART

---

crates/runner-nordic/src/board.rs
crates/runner-nordic/src/board/gpio.rs
crates/runner-nordic/src/board/uart.rs
crates/runner-nordic/src/main.rs

Add Nordic specific syscall for UART

---

.github/actions/ci-checks/action.yml
.github/workflows/ci.yml
scripts/ci.sh
scripts/publish.sh

And run the dry-run mode in CI.

Publish in dry-run mode by default

---

crates/cli-tools/CHANGELOG.md
crates/cli-tools/Cargo.lock
crates/cli-tools/Cargo.toml
crates/cli-tools/src/action.rs
crates/cli-tools/src/cmd.rs
crates/cli-tools/src/data/config.toml
crates/cli-tools/src/data/lib.rs
crates/cli-tools/src/fs.rs
crates/cli-tools/src/lib.rs
crates/cli-tools/test.sh
crates/cli/CHANGELOG.md
crates/cli/README.md
crates/cli/src/main.rs
crates/xtask/Cargo.lock
crates/xtask/Cargo.toml
crates/xtask/src/footprint.rs
crates/xtask/src/main.rs
scripts/ci-changelog.sh
scripts/publish.sh

Share the logic in cli-tools with xtask.

Add Rust applet support to the CLI

---

crates/runner-host/Cargo.lock
crates/runner-host/crates/web-server/Cargo.lock

Bump h2 from 0.3.24 to 0.3.26

---

crates/prelude/CHANGELOG.md
crates/prelude/Cargo.toml
crates/prelude/src/lib.rs
crates/prelude/src/platform/protocol.rs
crates/prelude/src/rpc.rs
crates/prelude/src/serial.rs
examples/rust/protocol/src/lib.rs

This is similar to Serial (#252) but for RPC.

Add RPC trait for platform::protocol

---

.github/workflows/ci.yml

This check is too noisy for a development branch.

Do not run changelog check

---

crates/error/CHANGELOG.md
crates/error/src/lib.rs
crates/logger/CHANGELOG.md
crates/logger/src/lib.rs
crates/runner-nordic/Cargo.toml
crates/runner-nordic/crates/header/Cargo.toml
crates/runner-nordic/crates/header/src/lib.rs
crates/store/test.sh
crates/store/tests/store.rs
crates/sync/CHANGELOG.md
crates/sync/src/lib.rs

See https://github.com/rust-lang/rust/issues/122105.
Fix #484

Work around unused-crate-dependencies false positive

---

.github/actions/ci-checks/action.yml
.github/workflows/pages.yml
crates/protocol/CHANGELOG.md
crates/protocol/crates/schema/src/main.rs
crates/protocol/src/lib.rs
crates/wire/CHANGELOG.md
crates/wire/src/lib.rs
scripts/sync.sh

Also enable the CI test for the platform protocol schema.

Implement Wire for never type

---

crates/wasm-bench/Cargo.lock
crates/wasm-bench/Cargo.toml
crates/wasm-bench/run.sh
crates/wasm-bench/src/main.rs
crates/wasm-bench/src/runtime/wasmtime.rs
crates/wasm-bench/test.sh

Add wasmtime for benchmark

---

crates/api-desc/CHANGELOG.md
crates/api-macro/CHANGELOG.md
crates/api/CHANGELOG.md
crates/board/CHANGELOG.md
crates/cli-tools/CHANGELOG.md
crates/cli/CHANGELOG.md
crates/error/CHANGELOG.md
crates/interpreter/CHANGELOG.md
crates/logger/CHANGELOG.md
crates/prelude/CHANGELOG.md
crates/protocol-usb/CHANGELOG.md
crates/protocol/CHANGELOG.md
crates/scheduler/CHANGELOG.md
crates/store/CHANGELOG.md
crates/stub/CHANGELOG.md
crates/sync/CHANGELOG.md
crates/wire-derive/CHANGELOG.md
crates/wire/CHANGELOG.md
scripts/publish.sh

Reset changelog tests during release

---

crates/board/CHANGELOG.md
crates/board/src/button.rs
crates/board/src/lib.rs
crates/board/src/platform.rs
crates/board/src/platform/protocol.rs
crates/board/src/radio.rs
crates/board/src/radio/ble.rs
crates/board/src/timer.rs
crates/board/src/uart.rs
crates/board/src/usb.rs
crates/board/src/usb/serial.rs
crates/board/test.sh
crates/scheduler/CHANGELOG.md
crates/scheduler/Cargo.lock
crates/scheduler/src/applet.rs
crates/scheduler/src/lib.rs
crates/scheduler/test.sh

Implement defmt::Format for board::Event

---

crates/scheduler/CHANGELOG.md
crates/scheduler/src/event.rs
crates/scheduler/src/event/button.rs
crates/scheduler/src/event/platform.rs
crates/scheduler/src/event/platform/protocol.rs
crates/scheduler/src/event/radio.rs
crates/scheduler/src/event/radio/ble.rs
crates/scheduler/src/event/timer.rs
crates/scheduler/src/event/uart.rs
crates/scheduler/src/event/usb.rs
crates/scheduler/src/event/usb/serial.rs

Implement defmt::Format for scheduler::event::Key

---

crates/cli-tools/CHANGELOG.md
crates/cli-tools/Cargo.lock
crates/cli-tools/Cargo.toml
crates/cli-tools/src/action.rs
crates/cli/CHANGELOG.md
crates/cli/Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs
crates/protocol-usb/CHANGELOG.md
crates/protocol-usb/src/host.rs
crates/protocol/crates/schema/Cargo.lock
crates/runner-host/Cargo.lock
crates/xtask/Cargo.lock

Also inline connection options to commands than need them.

Move platform-list action to cli-tools

---

crates/scheduler/CHANGELOG.md
crates/scheduler/src/call.rs
crates/scheduler/src/call/button.rs
crates/scheduler/src/call/crypto/ccm.rs
crates/scheduler/src/call/crypto/ec.rs
crates/scheduler/src/call/crypto/gcm.rs
crates/scheduler/src/call/gpio.rs
crates/scheduler/src/call/led.rs
crates/scheduler/src/call/platform/update.rs
crates/scheduler/src/call/timer.rs
crates/scheduler/src/call/uart.rs

Return an error instead of trapping for unimplemented API

---

crates/api-macro/CHANGELOG.md

Found by @exzachlyvv in #584. Fixing it now in `main` to avoid accidental releases with this bug.

Fix changelog

---

crates/runner-host/Cargo.lock
crates/runner-host/Cargo.toml
crates/runner-host/crates/web-server/src/lib.rs
crates/runner-host/src/board/debug.rs
crates/runner-host/src/cleanup.rs
crates/runner-host/src/main.rs

Also improve the behavior on exit. In particular, fix the runner exiting properly when the web client is closed.

Use tokio signal facilities

---

crates/interpreter/src/valid.rs

The first step towards building the side table.
The next step is to build the side table in `push_label()`, `pop_label()`, etc.
#46

Add side table to Context

---

crates/runner-host/src/main.rs

This will be useful for #577 which will introduce a file for the applet.

Use a flag for runner-host flash directory

---

crates/board/CHANGELOG.md
crates/board/src/usb/serial.rs

This is part of #278 and similar to #630.

Expose helpers for USB serial implementations

---

crates/runner-host/Cargo.toml
crates/runner-host/crates/web-server/src/lib.rs
crates/runner-host/src/board.rs
crates/runner-host/src/board/debug.rs
crates/runner-host/src/board/led.rs
crates/runner-host/src/main.rs
crates/runner-host/test.sh
crates/xtask/src/main.rs

This is needed for #278 and similar to #632.

Make runner-host interface dynamic

---

.cargo/config.toml
crates/cli-tools/CHANGELOG.md
crates/cli-tools/src/cmd.rs
crates/cli-tools/src/fs.rs
crates/cli/CHANGELOG.md
crates/cli/Cargo.toml
crates/cli/src/main.rs
crates/protocol-tokio/Cargo.lock
crates/runner-host/crates/web-client/.gitignore
crates/runner-host/crates/web-client/Makefile
crates/runner-host/crates/web-server/src/lib.rs
crates/runner-host/src/board/applet.rs
crates/runner-host/src/board/platform.rs
crates/runner-host/src/board/platform/update.rs
crates/runner-host/src/board/uart.rs
crates/runner-host/src/cleanup.rs
crates/runner-host/src/main.rs
crates/runner-host/src/web.rs
crates/runner-host/test.sh
crates/xtask/src/main.rs
scripts/artifacts.sh
scripts/wrapper.sh

Also embed the web-client in the host runner.
Fixes #278

Embed the host runner in the CLI

---

crates/runner-host/Cargo.lock
crates/runner-host/Cargo.toml
crates/runner-host/crates/web-client/src/main.rs
crates/runner-host/crates/web-server/Cargo.lock
crates/runner-host/crates/web-server/Cargo.toml
crates/runner-host/crates/web-server/src/lib.rs
crates/runner-host/crates/web-server/test.sh
crates/runner-host/src/main.rs
crates/runner-host/src/web.rs
crates/xtask/src/main.rs

Set web-client log level from web-server

---

crates/runner-host/src/board/usb.rs
crates/runner-host/src/main.rs

- Introduce delay to avoid busy loop
- Only run modprobe if needed

Small improvements around usbip in host runner

---

crates/runner-host/crates/web-client/src/app.rs

This was a regression I missed during review.

Fix web UI in GitHub Codespace

---

scripts/package.sh
scripts/publish.sh
scripts/upgrade.sh

Use cargo info instead of cargo search in publish script

---

crates/cli-tools/Cargo.lock
crates/cli/CHANGELOG.md
crates/cli/Cargo.lock
crates/protocol/crates/schema/Cargo.lock
crates/runner-host/Cargo.lock
crates/xtask/Cargo.lock
scripts/ci-changelog.sh

Include lock files in changelog for binaries

---

.github/actions/ci-checks/action.yml

See https://github.com/actions/runner-images/issues/10636

Assume ubuntu-latest is 24.04

---

crates/runner-nordic/memory.x
crates/runner-nordic/src/main.rs
crates/xtask/src/main.rs

Also use all available flash for native applets.

Make VID:PID of Nordic configurable

---

crates/wasm-bench/Cargo.lock
crates/wasm-bench/Cargo.toml
crates/wasm-bench/build.rs

It's taking at least 5 minutes out of `test-0` making it at least 12 minutes.

Reduce compile-time of wasmtime

---

crates/interpreter/src/exec.rs
crates/interpreter/src/module.rs
crates/interpreter/src/parser.rs
crates/interpreter/src/side_table.rs
crates/interpreter/src/valid.rs

Make `metadata()`, `parse_u16()` and `view()` generic

---

.github/workflows/ci.yml
crates/cli-tools/Cargo.lock
crates/cli-tools/Cargo.toml
crates/cli-tools/src/action.rs
crates/cli/Cargo.lock
crates/xtask/Cargo.lock
examples/rust/exercises/client/Cargo.lock
examples/rust/hsm/host/Cargo.lock
examples/rust/protocol/host/Cargo.lock
examples/rust/update/host/Cargo.lock
scripts/ci-applets.sh

Re-enable hwci host in dev/fast-interp

---

crates/runner-opentitan/Cargo.lock
crates/runner-opentitan/Cargo.toml
crates/runner-opentitan/src/board/platform/update.rs
crates/runner-opentitan/test.sh
scripts/ci-runners.sh

We need to tell ROM_EXT which next BL0 to use.

Fix platform update in opentitan

---

crates/prelude/CHANGELOG.md
crates/prelude/src/crypto/hash.rs
crates/runner-opentitan/memory.x
crates/xtask/src/main.rs
crates/xtask/src/opentitan.rs
examples/rust/hash_test/src/lib.rs
examples/rust/hash_test/src/main.rs
examples/rust/hash_test/test.sh

Also update the opentitan submodule and improve error message when missing HyperDebug.

Use more heap in opentitan with native

---

crates/cli-tools/CHANGELOG.md
crates/cli-tools/Cargo.lock
crates/cli-tools/Cargo.toml
crates/cli/CHANGELOG.md
crates/cli/Cargo.lock
crates/cli/Cargo.toml
crates/protocol-tokio/CHANGELOG.md
crates/protocol-tokio/Cargo.lock
crates/protocol-tokio/Cargo.toml
crates/protocol/crates/schema/Cargo.lock
crates/protocol/crates/schema/Cargo.toml
crates/runner-host/Cargo.lock
crates/runner-host/Cargo.toml
crates/runner-host/crates/web-client/Cargo.lock
crates/runner-host/crates/web-server/Cargo.lock
crates/runner-host/crates/web-server/Cargo.toml
crates/xtask/Cargo.lock
crates/xtask/Cargo.toml
examples/rust/exercises/client/Cargo.lock
examples/rust/hsm/host/Cargo.lock
examples/rust/protocol/host/Cargo.lock
examples/rust/protocol/host/Cargo.toml
examples/rust/update/host/Cargo.lock

Bump tokio from 1.44.0 to 1.44.2

---

crates/wasm-bench/Cargo.lock
crates/wasm-bench/Cargo.toml
crates/wasm-bench/build.rs
crates/wasm-bench/src/main.rs
crates/wasm-bench/src/runtime/wasmtime.rs

Bump Wasmtime from 30.0.2 to 32.0.0

---

scripts/setup.sh

Also update rustup submodule to fix CI

Fix missing dependency in setup script

---

crates/board/CHANGELOG.md
crates/board/Cargo.toml
crates/board/src/crypto.rs
crates/board/test.sh
crates/runner-nordic/Cargo.lock
crates/runner-nordic/Cargo.toml
crates/runner-nordic/src/board/crypto.rs

Also add software-crypto tests to the board to make sure they implement the API.

Add software-crypto-p256-{ecdh,ecdsa} to Nordic
