- book/src/applet/prelude/button1.rs
- crates/prelude/CHANGELOG.md
- crates/prelude/src/debug.rs
- crates/prelude/src/lib.rs
- examples/rust/button/src/lib.rs
- examples/rust/hello/src/lib.rs
- examples/rust/timer_test/src/lib.rs
This is useful to avoid conflicts with std because tests may use std.
> Rename println to avoid conflicts with std

- scripts/setup.sh
- scripts/system.sh
- scripts/wrapper.sh
On Ubuntu 22.04 LTS, there's only Node.js v12 which does not support AssemblyScript. We could also check the system version but that would add complexity for a feature that is not yet used.
Fixes #203
> Install Node.js v16 from nodesource instead of apt-get

- .github/workflows/ci.yml
- scripts/setup.sh
We would need to add it to the cache but it's big.
> Keep github version of rustup

- scripts/system.sh
Debian has the `usbip` binary in the `usbip` package while Ubuntu has it in the `linux-tools-common` package.
> Fix usbip package in ubuntu

- scripts/publish.sh
Ideally all scripts should be implemented in Rust, see #208.
> Assume bash for the publish script for simplicity

- crates/xtask/src/main.rs
Fixes a regression introduced by #280.
> Fix applet name to path conversion

- crates/runner-nordic/Cargo.lock
- crates/runner-nordic/Cargo.toml
- crates/runner-nordic/src/tasks.rs
- crates/runner-nordic/src/tasks/debug.rs
This was broken by #246 because `probe-rs` doesn't consider normal breakpoints as semi-hosting exit command.
Note that `./scripts/hwci.sh nordic` is currently slow with `--release` because of https://github.com/probe-rs/probe-rs/issues/1865
> Use semihosting for Nordic debug exit

- scripts/announce.sh
- scripts/ci.sh
- scripts/publish.sh
- scripts/upgrade.sh
By default pathspecs use fnmatch where `*` matches slashes too. The `**` is when using the glob magic word which sets `FNM_PATHNAME` when calling `fnmatch`.
> Fix unnecessary double asterisk

- crates/interpreter/CHANGELOG.md
- crates/interpreter/Cargo.lock
- crates/interpreter/Cargo.toml
- crates/interpreter/src/error.rs
- crates/interpreter/src/lib.rs
- crates/interpreter/src/parser.rs
- crates/interpreter/src/toctou.rs
- crates/interpreter/tests/spec.rs
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
This is a first step towards #42, but the most useful one for now.
> Explain what is unsupported in the interpreter

- crates/runner-nordic/Cargo.lock
- crates/runner-nordic/Cargo.toml
- crates/runner-nordic/src/main.rs
- crates/runner-nordic/src/storage.rs
- crates/sync/CHANGELOG.md
- crates/sync/src/lib.rs
- crates/sync/src/take.rs
This will be useful for #47 where the non-running flash partition will be a storage where the new firmware can be written.
> Permit multiple storage by sharing ownership of NVMC

- crates/xtask/src/main.rs
If the initial installation is interrupted, it's possible for the package.json to be present but the binary to be absent.
> Make sure AssemblyScript binary is present

- crates/runner-nordic/memory.x
- crates/xtask/src/main.rs
Otherwise the UICR registers are also reset which, among others, resets the PSELRESET registers that permits resetting the dev-board from the reset button.
> Do not erase the flash to reset the storage on Nordic

- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- scripts/wrapper.sh
This makes running `hwci.sh nordic` faster for `--release`.
> Update to probe-rs 0.22.0

- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/event/radio.rs
- crates/scheduler/src/event/usb.rs
It's not easy to test those without creating impossible configurations by enabling internal features. They will anyway be eventually tested when siblings are added, which is when it matters.
> Correctly gate events of nested APIs

- crates/prelude/CHANGELOG.md
- crates/prelude/src/allocator/wasm.rs
- crates/prelude/src/callback.rs
- crates/runner-nordic/crates/header/src/lib.rs
- crates/runner-nordic/src/allocator.rs
- crates/runner-nordic/src/storage.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/event.rs
- rust-toolchain.toml
Now that https://github.com/rust-lang/rust/issues/118609 is fixed. The previous nightly was broken and rolled-back in #338.
> Update toolchain to a working nightly

- crates/xtask/src/main.rs
This permits customizations like `runner nordic --probe-rs=--no-location` which are sometimes easier to read.
> Add --probe-rs flag to xtask runner

- crates/runner-host/Cargo.lock
- crates/runner-host/Cargo.toml
- crates/runner-host/src/main.rs
- crates/xtask/src/main.rs
This change allows developer to customize the web-server host & port, so it's easier to develop in remote environments.
> Add --web-host and --web-port flags to xtask and host runner

- .github/workflows/scorecard.yml
> Update scorecard action from v2 to v2.3.1

- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/event.rs
- crates/scheduler/src/event/radio.rs
- crates/scheduler/src/event/usb.rs
- crates/scheduler/src/lib.rs
Enabling a board feature automatically enables the applet feature, so it's enough to check for the board feature.
> Simplify cfg(all) between board and applet features in scheduler

- .github/workflows/ci.yml
It's rarely useful, since most often it's the changelog job failing.
> Disable fail-fast for checks

- crates/prelude/CHANGELOG.md
- crates/prelude/src/led.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call/led.rs
panic with an `InvalidArgument` error instead of trapping, also ensure we track the callers for #43.
For example the editing [`examples/rust/blink/src/lib.rs`](https://github.com/google/wasefire/blob/main/examples/rust/blink/src/lib.rs) to the following,
```rust
#![no_std]
wasefire::applet!();
use core::time::Duration;
fn main() {
// Make sure there is at least one LED.
let num_leds = led::count();
assert!(num_leds > 0, "Board has no LEDs.");
led::set(led_index, led::On);
}
```
and running `cargo xtask applet rust blink runner host `, would result in the following error:
```rust
Board initialized. Starting scheduler.                                                                                                                                                    
0.000848: panicked at …
```
> `led::{get, set}`: panic with an `InvalidArgument` error instead of trapping

- .gitattributes
- .github/actions/ci-checks/action.yml
- .github/workflows/ci.yml
- book/src/applet/run.md
- crates/board/CHANGELOG.md
- crates/board/Cargo.lock
- crates/board/Cargo.toml
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
- crates/store/CHANGELOG.md
- crates/store/Cargo.lock
- crates/store/Cargo.toml
- crates/store/fuzz/Cargo.lock
- crates/store/src/format.rs
- crates/store/src/lib.rs
- crates/store/src/store.rs
- crates/xtask/src/main.rs
- crates/xtask/src/textreview.rs
- scripts/ci-copyright.sh
- scripts/ci.sh
- scripts/log.sh
It should be possible to review text files on a screen without missing (or misinterpreting) any information contained in the file. This is needed because GitHub doesn't show trailing white-space, and UTF-8 is too permissive.
> Add a textreview check

- crates/board/CHANGELOG.md
- crates/board/Cargo.lock
- crates/board/Cargo.toml
- crates/board/src/crypto.rs
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
- crates/scheduler/src/applet.rs
- crates/scheduler/src/call/crypto/hash.rs
To resolve #176.
Please let me know any issue or improvement. Thanks!
1) I was wondering if there is any existing test in `wasefire/examples` that could be used to check if these changes break anything, especially using `FixedOutputReset` for the `Hmac` trait.
2) What Rust format tool do you use? As you can see, I use a different format tool and I'm happy to change to yours.
> Add LastError trait to check for error after using RustCrypto API

- crates/board/CHANGELOG.md
- crates/board/src/lib.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call/button.rs
- crates/scheduler/src/call/gpio.rs
- crates/scheduler/src/call/led.rs
- crates/scheduler/src/call/timer.rs
- crates/scheduler/src/call/uart.rs
Change `Id::new` to return a `Result` instead of an `Option` and migrate callers in the scheduler
> Change Id::new to return a Result instead of an Option

- .github/workflows/pages.yml
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call/radio/ble.rs
- crates/scheduler/src/call/timer.rs
- crates/scheduler/src/call/uart.rs
- crates/scheduler/src/call/usb/serial.rs
- crates/scheduler/src/lib.rs
Remove `impl From<Error> for Trap` as per [this comment](https://github.com/google/wasefire/pull/437#discussion_r1575107894) and migrate callers to use `map_err(|_| Trap)` instead for an explicit conversion.
> Remove `impl From<Error> for Trap`

- book/src/applet/prelude/button1.rs
- book/src/applet/prelude/button2.rs
- book/src/applet/prelude/timer.rs
- crates/prelude/CHANGELOG.md
- crates/prelude/src/_internal.rs
- crates/prelude/src/lib.rs
- examples/rust/button/src/lib.rs
- examples/rust/button_abort/src/lib.rs
- examples/rust/led/src/lib.rs
In #441 we changed `button::Listener::new` to never trap and never return an error, allowing users to use an early return of `?` if they don't care about the error. That PR `unwrap` ed the result instead of handling the error or propagating the error to its caller (sometimes ` main()`). 
This PR makes sure we properly handle the errors that we get from ` button::Listener::new` .
> Change prelude main to return a Result

- crates/prelude/CHANGELOG.md
- crates/prelude/src/gpio.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call/gpio.rs
- examples/rust/gpio_test/src/lib.rs
* Changes `scheduler/call/gpio.rs` to not trap and always return errors.
* Changes `prelude/gpio` to never panic and always return errors.
> Change gpio functions to never trap

- crates/prelude/CHANGELOG.md
- crates/prelude/src/internal.rs
- crates/prelude/src/lib.rs
FYI @lukeyeh : I discovered that Rust has a [`Termination`](https://doc.rust-lang.org/std/process/trait.Termination.html) trait in `std` for the exact purpose we added `MaybeUnwrap`. So I'm just renaming to be consistent with `std`. If the trait was in `core`, we could have used it, and just discarded the `ExitCode`. Applets in Wasefire are not really meant to exit, so a notion of exit code is not really useful.
> Rename MaybeUnwrap to Termination like std

- scripts/sync.sh
This is useful to bypass the check for the book examples, which over-triggers when moving between before and after #445.
> Add a --force flag to the sync script

- .github/workflows/ci.yml
- .gitmodules
- scripts/log.sh
- scripts/sync.sh
Moving from #466 into its own PR. #423
> Adding wasm/threads submodule.

- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call.rs
- crates/scheduler/src/call/button.rs
- crates/scheduler/src/call/crypto/ccm.rs
- crates/scheduler/src/call/crypto/ec.rs
- crates/scheduler/src/call/crypto/gcm.rs
- crates/scheduler/src/call/crypto/hash.rs
- crates/scheduler/src/call/debug.rs
- crates/scheduler/src/call/gpio.rs
- crates/scheduler/src/call/led.rs
- crates/scheduler/src/call/platform.rs
- crates/scheduler/src/call/platform/protocol.rs
- crates/scheduler/src/call/platform/update.rs
- crates/scheduler/src/call/radio/ble.rs
- crates/scheduler/src/call/rng.rs
- crates/scheduler/src/call/scheduling.rs
- crates/scheduler/src/call/store.rs
- crates/scheduler/src/call/store/fragment.rs
- crates/scheduler/src/call/timer.rs
- crates/scheduler/src/call/uart.rs
- crates/scheduler/src/call/usb/serial.rs
- crates/scheduler/src/lib.rs
This PR addresses the issue of handling both Trap and Error within the same try-block in the scheduler reply, resolving #463. Currently, the scheduler reply has the signature Result<Result<T, Error>, Trap>, which does not work well with try-blocks that only support one level of Result.
To resolve this, we introduce a new Failure enum that can represent either a Trap or an Error. The Failure type is defined in failure.rs, along with the Trap function. We also implement From traits for both Trap and Error to allow seamless conversion into the Failure type.
By updating the scheduler reply signature to Result<T, Failure>, we can now use the ? operator for both Trap and Error within the same try-block, making the code more concise and easier to read.
> Introduce Failure type for scheduler replies

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.lock
- crates/cli-tools/Cargo.toml
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
- scripts/ci-changelog.sh
This improves compile times and is more explicit. This used to be true for published libraries, but published binaries also matter.
> Do not rely on default features of dependencies

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/src/action.rs
For the target `wasm32-unknown-unknown` the mutable globals are activated by default. There seems to be a mismatch with wasm-opt, where it is not (yet?) the case.
Here is what is activatd by default for rustc (1.77.0):
```
~/wasefire % rustc --print=cfg  --target=wasm32-unknown-unknown  
debug_assertions
overflow_checks
panic="abort"
relocation_model="static"
target_abi=""
target_arch="wasm32"
target_endian="little"
target_env=""
target_family="wasm"
target_feature="mutable-globals"
target_feature="sign-ext"
target_has_atomic
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_equal_alignment="16"
target_has_atomic_equal_alignment="32"
target_has_atomic_equal_alignment="64" …
```
> Enable mutable globals in wasm-opt.

- crates/xtask/src/main.rs
- scripts/setup.sh
- scripts/system.sh
This seems to have changed in https://github.com/rust-lang/cargo/pull/13257.
Also do not install libusb-1.0 during setup. This doesn't seem necessary anymore.
> Do not strip debuginfo in debug build

- crates/error/CHANGELOG.md
- crates/error/Cargo.toml
- crates/error/src/lib.rs
- crates/protocol-usb/CHANGELOG.md
- crates/protocol-usb/Cargo.toml
- crates/protocol/CHANGELOG.md
- crates/protocol/Cargo.toml
- crates/wire/CHANGELOG.md
- crates/wire/Cargo.toml
- examples/rust/protocol/host/Cargo.lock
This is not a breaking change because 0.1.1-git was not published yet.
> Implement Error from core instead of std

- crates/board/CHANGELOG.md
- crates/board/src/debug.rs
Reverts google/wasefire#502
The conclusion from https://github.com/knurling-rs/defmt/issues/844#issuecomment-2143064192 is that `println` should just print its input (no timestamp, no location).
> Revert "Add TODO to remove println timestamp"

- crates/interpreter/CHANGELOG.md
- crates/interpreter/src/exec.rs
- crates/runner-nordic/src/board/uart.rs
- crates/store/CHANGELOG.md
- crates/store/fuzz/src/stats.rs
- crates/store/src/format.rs
- crates/store/src/lib.rs
- crates/store/src/store.rs
- examples/rust/protocol/host/src/main.rs
- rustfmt.toml
Note that there is a lot of off-by-one errors because of https://github.com/rust-lang/rustfmt/issues/6180.
> Enforce comment wrapping

- crates/interpreter/src/exec.rs
- crates/interpreter/src/parser.rs
- crates/interpreter/src/syntax.rs
- crates/interpreter/src/valid.rs
- crates/interpreter/tests/spec.rs
Execution up to the point that `atomic.wast` test passes. Notably that means notify, wait and fence are nor properly implemented yet, but everything else is. For the last three some basic checks are implemented though, like out of bounds and memory alignment.
Also changed the submodule to the feature branch with the fixed tests.
> Execution of wasm atomic ops with portable_atomics in the interpreter.

- scripts/upgrade.sh
We deliberately don't want to pin a version, because the whole point is to find the latest version.
> Wrap npm install command to bypass scorecard

- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
This breaks `cargo publish`. Also don't try to make the build reproducible now that we release and attest from Github. Also users installing from `cargo install` may still want debug paths.
> Do not use trim-paths in Cargo.toml

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.lock
- crates/cli-tools/Cargo.toml
- crates/cli-tools/src/fs.rs
- crates/cli-tools/src/lib.rs
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
- crates/protocol/crates/schema/Cargo.lock
- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
When using `copy_if_changed()` from 2 different sources `a.src` and `b.src` to `x.dst` in an ABA scenario, it is possible that the modification timestamp of `a.src` is not updated on the last run, and will thus not be copied. We introduce a copy of the source file next to the destination file to fix this issue.
> Fix copy_if_changed with multiple sources

- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/call/button.rs
- crates/scheduler/src/call/crypto/ccm.rs
- crates/scheduler/src/call/crypto/ec.rs
- crates/scheduler/src/call/crypto/gcm.rs
- crates/scheduler/src/call/crypto/hash.rs
- crates/scheduler/src/call/platform.rs
- crates/scheduler/src/call/platform/protocol.rs
- crates/scheduler/src/call/platform/update.rs
- crates/scheduler/src/call/radio/ble.rs
- crates/scheduler/src/call/rng.rs
- crates/scheduler/src/call/store.rs
- crates/scheduler/src/call/store/fragment.rs
- crates/scheduler/src/call/timer.rs
- crates/scheduler/src/call/uart.rs
- crates/scheduler/src/call/usb/serial.rs
- crates/scheduler/src/event.rs
- crates/scheduler/src/lib.rs
- crates/scheduler/src/native.rs
- crates/scheduler/src/protocol.rs
This is a first step towards dynamic loading and unloading of applets. For now, at most one applet may be loaded at a time.
> Make applet optional in scheduler

- crates/runner-nordic/src/main.rs
- crates/runner-nordic/src/storage.rs
This follows #562 towards dynamic loading and unloading of applets. The applet will be stored in a contiguous part of the flash.
> Add contiguous access to Nordic flash

- crates/runner-nordic/src/board/platform/update.rs
- crates/runner-nordic/src/storage.rs
This follows #568 towards dynamic loading and unloading of applets. The process of writing to flash can be shared between platform update and applet install.
> Abstract writing to flash on Nordic

- crates/interpreter/CHANGELOG.md
- crates/interpreter/Cargo.lock
- crates/interpreter/Cargo.toml
- crates/interpreter/src/error.rs
- crates/interpreter/src/lib.rs
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/runner-nordic/src/board/uart.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
- crates/wasm-bench/Cargo.lock
Part of #577 because starting an applet (dynamically) should not crash the platform in case of errors but instead propagate the error to the host.
> Implement From<interpreter::Error> for wasefire_error::Error

- crates/board/CHANGELOG.md
- crates/board/Cargo.lock
- crates/board/Cargo.toml
- crates/board/src/button.rs
- crates/board/src/lib.rs
- crates/board/src/timer.rs
- crates/board/src/uart.rs
- crates/cli-tools/Cargo.lock
- crates/cli/Cargo.lock
- crates/protocol-usb/Cargo.lock
- crates/protocol/crates/schema/Cargo.lock
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
- crates/scheduler/src/event.rs
- crates/scheduler/src/event/button.rs
- crates/scheduler/src/event/timer.rs
- crates/scheduler/src/event/uart.rs
- crates/scheduler/src/lib.rs
- crates/xtask/Cargo.lock
- examples/rust/protocol/host/Cargo.lock
The derivative crate is dead: https://github.com/mcarton/rust-derivative/issues/117.
> Use derive-where instead of derivative

- crates/interpreter/CHANGELOG.md
- crates/interpreter/Cargo.lock
- crates/interpreter/Cargo.toml
- crates/interpreter/test.sh
- crates/wasm-bench/run.sh
The `lru` crate needs the `hashbrown` feature to be no-std.
| Command | CoreMark | Time | RAM |
| --- | --- | --- | --- |
| `./run.sh nordic base` | 0.09058217 | 221.118s | 5384 |
| `./run.sh nordic base --features=wasefire-interpreter/cache` | 0.12708579 | 157.305s | 8700 |
Using the cache is 40% faster on this benchmark for 60% more RAM usage.
> Test and bench interpreter cache

- crates/api-macro/CHANGELOG.md
- crates/cli-tools/src/fs.rs
- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- crates/xtask/src/changelog.rs
- crates/xtask/src/main.rs
End goal ([bug](https://github.com/google/wasefire/issues/448)): Create script to automate updating CHANGELOG.md
This task will be done in 2 parts:
1. `xtask changelog ci`: validates all CHANGELOG.md files <-- this PR
2. `xtask changelog {major,minor,patch}`: automatically updates changelogs with a new description.
> Add "xtask changelog ci" to validate CHANGELOG.md files

- crates/board/CHANGELOG.md
- crates/board/src/platform/protocol.rs
The current implementation in protocol-usb matches the new documentation. The rationale for the change is to provide quick feedback to the host that the device is not ready to handle requests yet. This is not a big change because this part of the board API is not exposed to the applet API. It is exclusively used by the scheduler. We might want to do similar (and bigger) changes to other parts of the API (like UART or USB serial).
> Fix platform protocol API documentation

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.lock
- crates/cli-tools/Cargo.toml
- crates/cli-tools/src/action.rs
- crates/cli-tools/src/cmd.rs
- crates/cli-tools/src/fs.rs
- crates/cli-tools/src/lib.rs
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/main.rs
- crates/protocol-tokio/CHANGELOG.md
- crates/protocol-tokio/Cargo.toml
- crates/protocol/crates/schema/Cargo.lock
- crates/protocol/crates/schema/Cargo.toml
- crates/protocol/crates/schema/src/main.rs
- crates/runner-host/Cargo.lock
- crates/runner-host/Cargo.toml
- crates/runner-host/crates/web-server/Cargo.lock
- crates/runner-host/crates/web-server/Cargo.toml
- crates/runner-host/src/main.rs
- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- crates/xtask/src/footprint.rs
- crates/xtask/src/main.rs
- crates/xtask/src/textreview.rs
- examples/rust/protocol/host/Cargo.toml
> Make all CLIs async using tokio

- crates/interpreter/CHANGELOG.md
- crates/interpreter/src/exec.rs
Make `Thread::new` only take a single `Frame`.
#46
> Only take the initial frame in interpreter::Thread::new()

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.toml
- crates/cli-tools/src/lib.rs
- crates/cli-tools/test.sh
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
- crates/protocol-usb/CHANGELOG.md
- crates/protocol-usb/src/lib.rs
- crates/protocol/crates/schema/Cargo.lock
- crates/runner-host/Cargo.lock
- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- scripts/setup.sh
Also revert #618 since this is a better fix (`i686-unknown-linux-gnu` should only be used to compile a device, not a host, so it should not depend on `rusb`).
> Gate cli-tools actions behind a feature

- scripts/test-helper.sh
No need to compile one. We only use cargo check in testing (not cargo build), so we won't attempt to link the applet. The fact that we don't link is also important because the existing native applet could have been for another target triple.
> Just touch libapplet.a to ensure native applet

- crates/runner-host/Cargo.lock
- crates/runner-host/Cargo.toml
- crates/runner-host/src/board.rs
- crates/runner-host/src/board/platform.rs
- crates/runner-host/src/board/platform/protocol.rs
- crates/runner-host/src/board/usb.rs
- crates/runner-host/src/board/usb/serial.rs
- crates/runner-host/src/cleanup.rs
- crates/runner-host/src/main.rs
- crates/runner-host/test.sh
- crates/xtask/src/main.rs
- scripts/hwci.sh
This is needed for #278 since ideally want a single release of the host runner. And we still want this release to provide support for different transports. In particular because USB requires sudo and doesn't work in GitHub Codespaces.
> Make runner-host platform protocol dynamic over transport

- crates/xtask/src/changelog.rs
- crates/xtask/src/main.rs
Diff will clean up after PR #584 is merged
> Implement Display for Changelog. Hooked up to parsing validation.

- crates/interpreter/src/bit_field.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
- crates/interpreter/test.sh
> Compute delta_ip and delta_stp in side table

- .github/CODEOWNERS
We are affected by those GitHub issues:
- https://github.com/orgs/community/discussions/6292
- https://github.com/orgs/community/discussions/9636
For the first one, we created @ia0-review. For the second one, we have to make sure that a file has either exactly @ia0 as code owner, or both @ia0 and @ia0-review. This PR is fixing this second issue. It is also making sure @ia0 is the code owner of the CODEOWNERS file.
> Work around GitHub limitations regarding PR reviews

- crates/interpreter/tests/spec.rs
During development it can happen that a bug returns unsupported instead of failing. We want to detect those cases. Using a skip counter is an approximation. But since for almost all tests it is zero, then it's actually exact.
> Add a skip counter for unsupported and check it

- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/main.rs
- crates/cli/test.sh
- scripts/artifacts.sh
And show an error for the host command. Once we support self-update, we can suggest to self-update (with force in case it's the same version).
> Make sure CLI compiles with cargo install

- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/applet.rs
- crates/scheduler/src/protocol.rs
This was detected by nightly-2024-10-28 and must be fixed before we can upgrade all dependencies.
> Better gate applet-platform-protocol code

- .github/workflows/ci.yml
- scripts/artifacts.sh
Also add a checksum file in addition to the provenance attestation file.
> Release artifacts in tar.gz format to preserve file permissions

- crates/cli-tools/src/changelog.rs
- crates/xtask/src/main.rs
2 notes:
* This PR correctly writes back to Cargo.toml file however the original format is not preserved. Any easy way to do that?
* Not yet handling updates to crates that depend on originated change. That is next.
> Implement changelog update functionality.

- scripts/package.sh
- scripts/publish.sh
- scripts/upgrade.sh
And use it in `scripts/upgrade.sh` to update the `Cargo.toml` file in the right order.
In the end it didn't happen to be the dependency resolution problem, but it's still useful to have a way to iterate over crates in topological order.
> Define a topological order for all crates

- crates/interpreter/src/valid.rs
Jumping from "if without else" should be 1 step less than jumping from "if with else". For "if without else", we don't want to jump over the "end" because `exit_label()` need to be [called](https://github.com/zhouwfang/wasefire/blob/de6c7e889865736cb1f11877d5d4e1e9f50729a8/crates/interpreter/src/exec.rs#L788) at the "end". But for "if with else", we want to jump over the "else" because otherwise we would be forced to jump to the "end" at "else" (normally, we would reach "else" after executing the true branch of "if", and we should not execute the "else" branch).
This is equivalent to https://github.com/google/wasefire/blob/main/crates/interpreter/src/parser.rs#L566-L569, which will be deprecated with the side table applied in `exec.rs`.
#46
> Reduce delta_ip by 1 for "if without else" in validation

- crates/interpreter/src/valid.rs
When "if" has an "else", we should skip the entry for "else" in the side table. It was addressed in #690 during execution and should be moved to validation.
#46
> Increment delta_stp by 1 for "if with else" in validation

- crates/interpreter/src/exec.rs
- crates/interpreter/src/lib.rs
- crates/interpreter/src/parser.rs
- crates/interpreter/src/util.rs
- crates/interpreter/src/valid.rs
On my Linux Docker container:
1. 
CoreMark results of this PR: 37.991516 (in 18.695s), 36.7287 (in 19.258s)
CoreMark results of https://github.com/google/wasefire/pull/690: 37.101162 (in 19.133s), 37.39716 (in 18.996s)
Look very similar. Not sure about `nordic`.
2. 
CoreMark results of `main`: 28.791477 (in 18.09s), 28.814291 (in 17.734s)
So there does seem some minor performance improvement with `delta_ip` and `delta_stp`.
https://github.com/google/wasefire/issues/46
> Use instead of restoring side table for Loop

- crates/interpreter/src/parser.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
> Fix val_cnt for if

- crates/interpreter/src/exec.rs
It improves the performance by removing the costly `last_frame_values_cnt()`.
On linux, `CoreMark result: 39.795715 (in 17.853s)`. cf. CoreMark result was about 37 in 19s in #705.
#46
> Add prev_stack in Frame

- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
> Remove `Option` in side table creation

- examples/rust/exercises/test.sh
Now that https://github.com/rust-lang/cargo/issues/8010 has been fixed.
> Properly disable warnings in unsolved exercise tests

- crates/interpreter/src/module.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
> Return generalized side table from validation

- crates/interpreter/src/module.rs
- crates/interpreter/src/valid.rs
The next step is to add `Verify` with optimizations.
#46
> Add empty `ValidMode` and `Prepare`

- .github/workflows/ci.yml
The `hwci host` job may "freeze" because of process management in shell.
> Shorten timeout of matrix jobs to 15 minutes

- crates/interpreter/src/lib.rs
- crates/interpreter/src/module.rs
- crates/interpreter/src/parser.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
> Add the `Verify` mode

- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
Based on [this design](https://github.com/google/wasefire/pull/726#discussion_r1942421525).
#46
> Make `next_branch_table()` return value

- crates/interpreter/Cargo.lock
- crates/interpreter/Cargo.toml
- crates/interpreter/src/module.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/Cargo.lock
- crates/wasm-bench/Cargo.lock
> Use `[u8]` instead of `[u16]` to not rely on alignment

- crates/interpreter/src/valid.rs
> Complete implementation for `Verify`

- crates/runner-host/Cargo.toml
This is useful until #42 is fixed, by using `RUST_BACKTRACE=1`.
> Enable interpreter/debug in runner-host/debug

- crates/runner-nordic/src/main.rs
- examples/rust/opensk/src/lib.rs
The serial still works with it and it was the reason to use 16c0:27dd.
> Use 1915:521f for Nordic USB VID:PID

- crates/wasm-bench/Cargo.lock
- crates/wasm-bench/Cargo.toml
- crates/wasm-bench/build.rs
- crates/wasm-bench/run.sh
- crates/wasm-bench/src/main.rs
- crates/wasm-bench/src/runtime/wasmi.rs
- crates/wasm-bench/src/runtime/wasmtime.rs
- crates/wasm-bench/test.sh
- taplo.toml
| Target | Runtime | Perf | Flash | RAM |
| --- | --- | --- | --- | --- |
| Linux | Base | 33.1 | | |
| Linux | Wasm3 | 2531 (76x) | | |
| Linux | Wasmi | 1556 (47x) | | |
| Linux | Wasmtime | 22652 (684x) | | |
| Nordic | Base | 0.0925 | 144920 | 5384 |
| Nordic | Wasmi | 4.6 (50x) | 856552 (5.9x) | 91872 (17x) |
| Nordic | Wasmtime | OOM | 659260 (4.5x) | >264912 (>49x) |
Note that the CoreMark module uses 7771 bytes of Flash, which are included in the numbers given above.
> Use Pulley for Wasmtime in wasm-bench

- crates/wasm-bench/.cargo/config.toml
- crates/wasm-bench/Cargo.toml
- crates/wasm-bench/build.rs
- crates/wasm-bench/run.sh
Results for Nordic only:
| Runtime | Opt | Result | Flash | RAM |
| --- | --- | --- | --- | --- |
| Base | Perf | 0.0937 | 144708 - 7771 = 136937 | 5416 |
| Base | Size | 0.0462 | 97536 - 7771 = 89765 | 5432 |
| Wasmi | Perf | 4.55 (49x) | 855240 - 7771 = 847469 (6.2x) | 91872 (17x) |
| Wasmi | Size | 2.15 (47x) | 466628 - 7771 = 458857 (5.1x) | 91872 (17x) |
| Wasmtime | Perf | OOM | 658292 - 264912 = 393380 (2.9x) | >264912 |
| Wasmtime | Size | OOM | 529936 - 264912 = 265024 (3x) | >264912 |
> Support optimizing for size for wasm-bench

- crates/interpreter/CHANGELOG.md
- crates/interpreter/Cargo.lock
- crates/interpreter/Cargo.toml
- crates/interpreter/src/exec.rs
- crates/interpreter/src/module.rs
- crates/runner-host/Cargo.lock
- crates/runner-nordic/Cargo.lock
- crates/scheduler/CHANGELOG.md
- crates/scheduler/Cargo.lock
- crates/scheduler/Cargo.toml
- crates/wasm-bench/Cargo.lock
This was only present for convenience and not meant to be public.
> Remove Default implementation for Module in interpreter

- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- scripts/wrapper.sh
This fixes an issue with defmt content being dropped, affecting the opensk example. See https://github.com/knurling-rs/defmt/issues/825.
> Bump probe-rs from 0.25.0 to 0.27.0

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/src/action.rs
- crates/error/CHANGELOG.md
- crates/error/src/lib.rs
- crates/logger/CHANGELOG.md
- crates/logger/src/lib.rs
- crates/one-of/CHANGELOG.md
- crates/one-of/src/lib.rs
- crates/runner-nordic/Cargo.toml
- crates/runner-nordic/crates/header/Cargo.toml
- crates/runner-nordic/crates/header/src/lib.rs
- crates/sync/CHANGELOG.md
- crates/sync/src/lib.rs
- crates/xtask/src/main.rs
This avoids false positives until https://github.com/rust-lang/rust/issues/122105 is fixed. We anyway run similar commands without `-Zbuild-std` in CI which should catch most if not all unused crate dependencies.
> Disable unused-crate-dependencies when using -Zbuild-std

- .github/workflows/ci.yml
- crates/interpreter/src/format.rs
- crates/interpreter/src/lib.rs
- crates/interpreter/src/module.rs
- crates/interpreter/src/parser.rs
- crates/interpreter/src/side_table.rs
- crates/interpreter/src/toctou.rs
- crates/interpreter/src/util.rs
- crates/interpreter/src/valid.rs
- crates/interpreter/test.sh
- crates/interpreter/tests/spec.rs
> Serialize side table and integrate `verify`

- crates/interpreter/src/side_table.rs
- crates/interpreter/src/valid.rs
The main changes are:
- Do not create a branch table entry for unreachable code. This saves space and permits a uniform treatment of branches.
- Use the correct stack length for the Loop branch target (we're taking the branch before being in the label, so the current stack needs to be added).
- Take the Else source and target branches at the correct time (i.e. when the stack is the expected one such that the stack length is correctly computed).
> Fix branch table logic

- crates/interpreter/tests/spec.rs
This way we can make sure which part of it is unsupported, namely the large table.
> Modify the br_table test before parsing

- crates/runner-host/src/board/usb.rs
- crates/runner-nordic/src/main.rs
- examples/rust/opensk/src/blink.rs
- examples/rust/opensk/src/env/user_presence.rs
- examples/rust/opensk/src/lib.rs
The CTAP report descriptor was wrong, the timer logic was flipped, and we were having nested `ctap::Listener::new(Read)` (the one in `main()` and the one in `user_presence.rs`). This PR also adds winking support which fixes the nested listener issue at the same time.
> Fix opensk example

- .cargo/config.toml
- .github/workflows/ci.yml
- scripts/ci-cache.sh
- scripts/wrapper.sh
We can't run the whole CI in a single runner because we reach the 14G SSD when adding OpenTitan (probably because of all the RISC-V compilation artifacts). So we won't do anything special anymore on `schedule` triggered workflow and we build the cache by simply compiling all cargo wrappers.
> Build cache directly instead of running everything

- scripts/upgrade.sh
- scripts/wrapper.sh
We are anyway living at "head" (recent nightly, etc). This also simplifies dealing with security fixes. Ideally this would be controlled by #583.
> Stop trying to use minimal versions

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.lock
- crates/cli-tools/Cargo.toml
- crates/cli-tools/src/action/usb_serial.rs
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/xtask/Cargo.lock
- crates/xtask/Cargo.toml
- examples/rust/exercises/client/Cargo.lock
- examples/rust/exercises/client/Cargo.toml
- examples/rust/exercises/client/src/main.rs
- examples/rust/hsm/host/Cargo.lock
- examples/rust/hsm/host/Cargo.toml
- examples/rust/hsm/host/src/main.rs
- examples/rust/protocol/host/Cargo.lock
- examples/rust/update/host/Cargo.lock
- examples/rust/update/host/Cargo.toml
- examples/rust/update/host/src/main.rs
See https://github.com/serialport/serialport-rs/issues/243.
> Revert serialport from 4.7.0 to 4.6.1 due to regression

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/Cargo.lock
- crates/cli-tools/Cargo.toml
- crates/cli-tools/src/action.rs
- crates/cli-tools/src/action/usb_serial.rs
- crates/cli/CHANGELOG.md
- crates/cli/Cargo.lock
- crates/protocol/crates/schema/Cargo.lock
- crates/runner-host/Cargo.lock
- crates/runner-host/crates/web-server/Cargo.lock
- crates/xtask/Cargo.lock
- examples/rust/exercises/client/Cargo.lock
- examples/rust/hsm/host/Cargo.lock
- examples/rust/protocol/host/Cargo.lock
- examples/rust/update/host/Cargo.lock
The following findings are not fixed:
- `paste` is "finished: https://github.com/rustsec/advisory-db/pull/2215#issuecomment-2709315704
- `ring` will be fixed by OpenSK
- `proc-macro-error` will be fixed by Yew: https://github.com/yewstack/yew/pull/3752
> Fix security code scanning alerts

- crates/interpreter/src/exec.rs
- crates/interpreter/src/lib.rs
- crates/interpreter/src/util.rs
- crates/interpreter/src/valid.rs
> Improve `offset_front()`

- examples/rust/opensk/src/env.rs
- examples/rust/opensk/src/env/hid_connection.rs
- examples/rust/opensk/src/lib.rs
This way, the applet can sleep as long as nothing happens. (The platform doesn't because it has to check USB regularly, but still sleeps between USB interrupts.)
> Only timeout on recv if winking

- crates/cli-tools/CHANGELOG.md
- crates/cli-tools/src/action.rs
Otherwise reruning the command will wrongly succeed.
> Delete applet file if optimizing fails

- crates/runner-host/Cargo.lock
- crates/runner-host/Cargo.toml
- examples/rust/opensk/README.md
This permits running a native opensk on the host runner.
> Fix usb-ctap on host runner

- .gemini/styleguide.md
- examples/rust/nordic_ble_adv/src/lib.rs
Otherwise the platform won't call the callback until a new packet is received.
> Fix nordic_ble_adv applet to read all available packets

- crates/runner-host/src/main.rs
This is to avoid infinite loop when invoking the host runner from the CLI.
> Return an error code with --help for host runner

- crates/interpreter/CHANGELOG.md
- crates/interpreter/src/exec.rs
- crates/scheduler/CHANGELOG.md
- crates/scheduler/src/applet.rs
- crates/scheduler/src/applet/store/wasm.rs
The scheduler panics when trying to access the memory of an applet when no threads are running. This only affects wasm and not pulley.
> Fix callbacks accessing memory when main exits
